[tool.ruff]

select = [
    "E",
    "F",
    "W",
    "I",
    "B",
    "N",
    "A",
    "C4",
    "C9",
    "Q",
    "ARG",
    "PD",
    "NPY",
    "ERA"]

#D -> PyDocStyle -> Aggressive

ignore = [
    "N999",
    "B008",
    "PD011",]

show-source = true

# Allow autofix for all enabled rules (when `--fix`) is provided.
# fixable = ["A", "B", "C", "D", "E", "F", "..."]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "*env",
    "env/",
    "*test*",
]
per-file-ignores = {}

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

line-length = 120
# black use 88
# flake8 120

[tool.ruff.flake8-quotes]
inline-quotes = "double"

[tool.ruff.mccabe]
max-complexity = 12

#[tool.ruff.per-file-ignores]
#"__init__.py" = ["F401"]