"""add column for number of token and if the user paided

Revision ID: 1f1bea04152a
Revises: bb6eb03419e3
Create Date: 2023-06-07 15:33:20.326788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f1bea04152a'
down_revision = 'bb6eb03419e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('is_paid', sa.Boolean(), nullable=True))
    op.add_column('t_user', sa.Column('data_first_paid', sa.DateTime(timezone=True), nullable=True))
    op.add_column('t_user', sa.Column('tokens_to_be_paid', sa.Integer(), nullable=True))
    op.add_column('t_user', sa.Column('total_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_user', 'total_tokens')
    op.drop_column('t_user', 'tokens_to_be_paid')
    op.drop_column('t_user', 'data_first_paid')
    op.drop_column('t_user', 'is_paid')
    # ### end Alembic commands ###
