"""Insert telegram table complete

Revision ID: 2e5646771a99
Revises: e64b1d96a1bd
Create Date: 2023-06-19 15:28:34.718423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e5646771a99'
down_revision = 'e64b1d96a1bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_telegram',
    sa.Column('id_t_telegram', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_chat', sa.String(), nullable=True),
    sa.Column('unique_hash_code', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('last_access', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['t_user.id_t_user'], ),
    sa.PrimaryKeyConstraint('id_t_telegram'),
    sa.UniqueConstraint('unique_hash_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_telegram')
    # ### end Alembic commands ###
