"""add id_chat integer

Revision ID: 318576544037
Revises: da07f1b3b240
Create Date: 2023-06-21 16:16:13.156922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '318576544037'
down_revision = 'da07f1b3b240'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
