"""add language

Revision ID: 31ac00618098
Revises: 3f6054480a1f
Create Date: 2023-05-25 16:33:53.165912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31ac00618098'
down_revision = '3f6054480a1f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_company', sa.Column('language', sa.String(), nullable=True))
    op.drop_constraint('t_instagram_un', 't_instagram', type_='unique')
    op.add_column('t_user', sa.Column('language', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_user', 'language')
    op.create_unique_constraint('t_instagram_un', 't_instagram', ['posturl', 'id_company', 'id_user', 'post'])
    op.drop_column('t_company', 'language')
    # ### end Alembic commands ###
