"""id_chat telegram as INTEGER

Revision ID: 5164e8d4598c
Revises: e92b760bf328
Create Date: 2023-06-21 19:01:25.713129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5164e8d4598c'
down_revision = 'e92b760bf328'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_telegram', 'id_chat',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='id_chat::integer'
               )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_telegram', 'id_chat',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='id_chat::VARCHAR')
    # ### end Alembic commands ###
