"""add messages ID in telegram

Revision ID: 66292f48fd0d
Revises: 5164e8d4598c
Create Date: 2023-06-23 16:12:52.059244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66292f48fd0d'
down_revision = '5164e8d4598c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_telegram', sa.Column('message_id_image', sa.Integer(), nullable=True))
    op.add_column('t_telegram', sa.Column('message_id_description', sa.Integer(), nullable=True))
    op.add_column('t_telegram', sa.Column('message_id_prompt', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_telegram', 'message_id_prompt')
    op.drop_column('t_telegram', 'message_id_description')
    op.drop_column('t_telegram', 'message_id_image')
    # ### end Alembic commands ###
