"""post_url unique

Revision ID: 7945c999bd70
Revises: 8e0d26c8ce00
Create Date: 2023-04-30 17:03:37.023145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7945c999bd70'
down_revision = '8e0d26c8ce00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('t_instagram_un', 't_instagram', ['posturl', 'id_company', 'id_user', 'post'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('t_instagram_un', 't_instagram', type_='unique')
    # ### end Alembic commands ###
