"""Primo commit

Revision ID: 8e0d26c8ce00
Revises: 
Create Date: 2023-04-30 00:02:49.993878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e0d26c8ce00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_company',
    sa.Column('id_t_company', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('url_instagram', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_t_company'),
    sa.UniqueConstraint('name')
    )
    op.create_table('t_instagram',
    sa.Column('id_t_instagram', sa.Integer(), nullable=False),
    sa.Column('id_company', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('post', sa.String(), nullable=True),
    sa.Column('image_description', sa.String(), nullable=True),
    sa.Column('hashtags', sa.String(), nullable=True),
    sa.Column('mentions', sa.String(), nullable=True),
    sa.Column('tagged_users', sa.String(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('typename', sa.String(), nullable=True),
    sa.Column('mediacount', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('posturl', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_t_instagram')
    )
    op.create_index('idx_instagram_unique_cols', 't_instagram', ['id_company', 'id_user', 'post', 'image_description', 'hashtags', 'mentions', 'tagged_users', 'likes', 'comments', 'date', 'location', 'typename', 'mediacount', 'title', 'posturl'], unique=True, postgresql_where=sa.text('post IS NOT NULL'))
    op.create_table('t_user',
    sa.Column('id_t_user', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('last_access', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id_t_user'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_user')
    op.drop_index('idx_instagram_unique_cols', table_name='t_instagram', postgresql_where=sa.text('post IS NOT NULL'))
    op.drop_table('t_instagram')
    op.drop_table('t_company')
    # ### end Alembic commands ###
