"""change telegram save message pattern

Revision ID: b1c254438841
Revises: 66292f48fd0d
Create Date: 2023-06-24 10:20:19.771233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1c254438841'
down_revision = '66292f48fd0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_telegram', sa.Column('message_description', sa.String(), nullable=True))
    op.add_column('t_telegram', sa.Column('message_prompt', sa.Text(), nullable=True))
    op.drop_column('t_telegram', 'message_id_description')
    op.drop_column('t_telegram', 'message_id_image')
    op.drop_column('t_telegram', 'message_id_prompt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_telegram', sa.Column('message_id_prompt', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('t_telegram', sa.Column('message_id_image', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('t_telegram', sa.Column('message_id_description', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('t_telegram', 'message_prompt')
    op.drop_column('t_telegram', 'message_description')
    # ### end Alembic commands ###
