"""add user-telegram

Revision ID: da07f1b3b240
Revises: 2e5646771a99
Create Date: 2023-06-21 15:58:40.086702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da07f1b3b240'
down_revision = '2e5646771a99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_telegram', sa.Column('id_user_telegram', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 't_telegram', ['id_chat'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_telegram', type_='unique')
    op.drop_column('t_telegram', 'id_user_telegram')
    # ### end Alembic commands ###
