"""Insert telegram table

Revision ID: e64b1d96a1bd
Revises: 947b9da0d6f3
Create Date: 2023-06-19 15:27:20.578300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e64b1d96a1bd'
down_revision = '947b9da0d6f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
