"""remove unique_hash_code from telegram and add it to user

Revision ID: e92b760bf328
Revises: a044c1383e26
Create Date: 2023-06-21 16:27:18.888863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e92b760bf328'
down_revision = 'a044c1383e26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_telegram', 'unique_hash_code')
    op.add_column('t_user', sa.Column('unique_hash_code', sa.String(), nullable=True))
    op.create_unique_constraint(None, 't_user', ['unique_hash_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_user', type_='unique')
    op.drop_column('t_user', 'unique_hash_code')
    op.add_column('t_telegram', sa.Column('unique_hash_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
