"""add tokens inside company table

Revision ID: ea07de1bb133
Revises: a2e901056d43
Create Date: 2023-06-14 10:31:07.702682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea07de1bb133'
down_revision = 'a2e901056d43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_company', sa.Column('tokens_to_be_paid', sa.Integer(), nullable=True))
    op.add_column('t_company', sa.Column('total_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_company', 'total_tokens')
    op.drop_column('t_company', 'tokens_to_be_paid')
    # ### end Alembic commands ###
