name: copy files
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file
      uses: canastro/copy-file-action@master
      with:
        source: "app/config/config-example.py"
        target: "app/config/config.py"
    - name: Add and commit changes
      run: |
        git config --local user.email "alegoller@gmail.com"
        git config --local user.name "Alessandro"
        git add app/config/config.py
        git commit -m "Add config file"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
