name: PIPELINE
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install -r requirements-dev.txt
    - name: Run ruff
      run: ruff app --fix
    - name: Run type checking
      run: mypy app --exclude app/dependency.py --exclude main.py
    - name: Run pylint
      run: pylint app
    - name: Check for errors
      run: exit $(($? > 0))
  cd:
    # Only run this job if the "build" job passes
    needs: build
    # Only run this job if new work is pushed to "main"
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    # Set up operating system
    runs-on: ubuntu-latest
    # Define job steps
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install -r docs/requirements.txt
        pip install python-semantic-release
    # Penso non possa aggiungerlo cosi
    - name: Build documentation
      run: make html --directory docs/
    - name: Python Semantic Release
      uses: relekang/python-semantic-release@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
