name: PIPELINE
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Run type checking
      run: mypy app --exclude app/dependency.py --exclude main.py
    - name: Run pylint
      run: pylint app
    - name: Run tests
      run: coverage run --source=app -m pytest
    - name: Check for errors
      run: exit $(($? > 0))